In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits
digits=load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test=train_test_split(digits.data, digits.target, test_size=0.2)

In [29]:
lr=LogisticRegression(max_iter=100000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9165275459098498

In [14]:
svm=SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.975

In [43]:
rf=RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9298831385642737

In [16]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [30]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [31]:
get_score(lr, x_train, x_test, y_train, y_test)

0.9165275459098498

In [20]:
get_score(svm, x_train, x_test, y_train, y_test)

0.975

In [44]:
get_score(rf, x_train, x_test, y_train, y_test)

0.9248747913188647

In [22]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
score_l=[]
score_svm=[]
score_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test=digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(lr, x_train, x_test, y_train, y_test))
    score_svm.append(get_score(svm, x_train, x_test, y_train, y_test))
    score_rf.append(get_score(rf, x_train, x_test, y_train, y_test))

In [38]:
score_l

[0.9248747913188647, 0.9382303839732888, 0.9232053422370617]

In [39]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [40]:
score_rf

[0.9248747913188647, 0.9465776293823038, 0.9198664440734557]

In [45]:
from sklearn.model_selection import cross_val_score

In [48]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [50]:
cross_val_score(SVC(),digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [51]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.93611111, 0.92777778, 0.96657382, 0.9637883 , 0.9275766 ])