In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
df=pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
## calculate the median of bathrooms and replace that number with NaN values
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

4

In [9]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [14]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
reg.intercept_

221323.00186540402

In [16]:
reg.predict([[3000,3,40]])

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [17]:
reg.predict([[2500,4,5]])

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

# Exercise

In [44]:
df=pd.read_csv('hiring.csv')
df

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [45]:
# fill missing value with zero
df.experience.fillna('zero', inplace=True)
df

experience  test_score  interview_score  salary($)
0       zero         8.0                9      50000
1       zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [46]:
## convert word into numbers
!pip install word2number
from word2number import w2n
df['experience'] = df['experience'].astype(str).apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         NaN                7      72000
7          11         7.0                8      80000

In [48]:
median_testscore= df.test_score.median()
median_testscore

8.0

In [50]:
df.test_score=df.test_score.fillna(median_testscore)
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         8.0                7      72000
7          11         7.0                8      80000

In [51]:
df.rename(columns={'salary($)': 'salary'}, inplace=True)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [52]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score']], df.salary)

LinearRegression()

In [53]:
reg.predict([[2, 9, 6]])

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [54]:
reg.predict([[12, 10, 10]])

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [56]:
import joblib

In [57]:
joblib.dump(reg, 'reg_joblib')

['reg_joblib']

In [58]:
rj= joblib.load('reg_joblib')

In [60]:
reg.predict([[10, 9, 5]])

/Users/shreybhardwaj/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73504.36681223])